language: java

sudo: false

# http://docs.travis-ci.com/user/caching/#Arbitrary-directories
cache:
  directories:
  - $HOME/.m2

jdk:
  - oraclejdk11
  - oraclejdk8

before_script:
  - docker build -t location-server location-server/
  - docker run -d --name location-server -p 31836:9000 location-server

matrix:
  fast_finish: true
