---
os: linux
dist: xenial
language: java

cache:
  directories:
    - $HOME/.m2

jdk:
  - openjdk11
  - openjdk8

before_script:
  - cd location-server && ./start-location.sh && cd ..

script:
  - mvn test -B -Dtestng.runHttpRemoteTests=1 -Dtestng.runS3RemoteTests=1

jobs:
  fast_finish: true
